services:
  php:
    build:
      context: ./php83
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - /var/opt:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    working_dir: /etc/nginx
    volumes:
      - /etc/nginx:/etc/nginx/conf.d
      - /var/opt:/var/www/html

  mysql:
    image: mysql:8.2.0
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - work-data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: Hunter.123

  redis:
    image: redis:7.2.3
    ports:
      - 6379:6379
    volumes:
      - study-data:/data

volumes:
  work-data: